yarnPath: .yarn/releases/yarn-4.5.1.cjs
enableGlobalCache: false

packageExtensions:
  "@typescript-eslint/utils@8.12.2":
    dependencies:
      eslint: "^9.13.0"
  "@typescript-eslint/eslint-plugin@8.12.2":
    dependencies:
      eslint: "^9.13.0"
  "@typescript-eslint/parser@8.12.2":
    dependencies:
      eslint: "^9.13.0"